import { Effect } from "effect"
import { existsSync, lstatSync, mkdirSync, readlinkSync, rmSync, symlinkSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import * as Exec from "./Exec.ts"

/** Kiln's SDK next to this file: in a checkout `<repo>/sdk/node_modules`, in the Nix package the same layout. */
export const sdkPath = resolve(dirname(import.meta.path), "../../../sdk/node_modules")

const tsconfig = {
  compilerOptions: {
    target: "ES2024",
    module: "preserve",
    moduleResolution: "bundler",
    lib: ["ES2024"],
    types: [],
    strict: true,
    exactOptionalPropertyTypes: true,
    noUncheckedIndexedAccess: true,
    allowImportingTsExtensions: true,
    verbatimModuleSyntax: true,
    noEmit: true,
    skipLibCheck: true,
  },
  include: ["*.ts"],
}

const names = (dir: string, output: string, system: string) =>
  Exec.run(["nix", "eval", "--json", `${dir}#${output}.${system}`, "--apply", "builtins.attrNames"], { cwd: dir }).pipe(
    Effect.map((json) => JSON.parse(json) as ReadonlyArray<string>),
    Effect.orElseSucceed(() => [] as ReadonlyArray<string>),
  )

/**
 * `kiln gen`: writes `.kiln/flake.ts` from the flake's outputs, a tsconfig for editors, and links
 * `.kiln/node_modules` to Kiln's SDK so `@kiln/core`, `@kiln/std` and `effect` resolve.
 */
export const gen = (repo: string, system: string) =>
  Effect.gen(function*() {
    const dir = resolve(repo)
    const kiln = join(dir, ".kiln")
    mkdirSync(kiln, { recursive: true })
    const [packages, checks, devShells] = yield* Effect.all(
      [names(dir, "packages", system), names(dir, "checks", system), names(dir, "devShells", system)],
      { concurrency: "unbounded" },
    )
    const list = (xs: ReadonlyArray<string>) => `[${xs.map((x) => JSON.stringify(x)).join(", ")}]`
    writeFileSync(
      join(kiln, "flake.ts"),
      `// Generated by \`kiln gen\` from the flake's outputs. Run it again after adding or renaming outputs.
import { Flake } from "@kiln/core"

export const flake = Flake.make({
  packages: ${list(packages)},
  checks: ${list(checks)},
  devShells: ${list(devShells)},
})
`,
    )
    writeFileSync(join(kiln, "tsconfig.json"), `${JSON.stringify(tsconfig, null, 2)}\n`)
    writeFileSync(join(kiln, ".gitignore"), "node_modules\n")
    link(join(kiln, "node_modules"), sdkPath)
    return { packages, checks, devShells }
  })

export const link = (path: string, target: string) => {
  if (existsSync(path) || isLink(path)) {
    if (isLink(path) && readlinkSync(path) === target) return
    rmSync(path, { recursive: true, force: true })
  }
  symlinkSync(target, path)
}

const isLink = (path: string) => {
  try {
    return lstatSync(path).isSymbolicLink()
  } catch {
    return false
  }
}
